### PR TITLE
Layout Styles Fixes

### PR DESCRIPTION
**Pull request by andemerie**

### CODE REVIEW

**Comment by andemerie** [comment]
[Layout](https://trello.com/c/N5s2JlPa/422-layout)

**Review by UladBohdan — CHANGES_REQUESTED** [review]
Could you provide a brief description of what were you fixing?..

I guess it's a Sidebar bug and "close-cross" to be on top of sidebar - this seems to be broken:
Screen Shot 2020-01-10 at 18 33 18
(Chrome, on all types of screens)

**Comment by andemerie** [comment]
[Sidebar](https://trello.com/c/5xGjIKSD/428-sidebar)

**Comment by andemerie** [comment]
I fixed bugs checked in these cards:  [Layout](https://trello.com/c/N5s2JlPa/422-layout) and  [Sidebar](https://trello.com/c/5xGjIKSD/428-sidebar)

**Review by UladBohdan — CHANGES_REQUESTED** [review]
Still does not look fixed to me :(
The "cross" is supposed to be floating, right?

Screen Shot 2020-01-15 at 12 19 21

**Comment by Drapegnik** [comment]
@andemerie

**Review by UladBohdan — APPROVED** [review]

**Review by Drapegnik — APPROVED** [review]

**Pull request merged**
