### PR TITLE
🔥Main Page & Login Updates

### PR DESCRIPTION
**Pull request by Drapegnik**
## done
* add `TextWithBr` for separating lines in `Diary`
* fix pagination bug
* 🔥add next articles chunk prefetch -> for user looks like blazing fast loading 🔥 
* add opacity, relative publication date & edit button on tiles:
screen shot 2018-06-11 at 02 59 38
screen shot 2018-06-11 at 03 00 46

* use the same format on article page:
screen shot 2018-06-11 at 03 13 14

## known issues
* in case (`!publishAt`):
screen shot 2018-06-11 at 03 03 43

* add `CompleteRow` component for inserting empty tiles
* hide signup
* add filtering GA tracking actions with:
```js
meta: {
	ga: true
}
```

> P.S: please test pagination & loading

### CODE REVIEW

**Comment by Drapegnik** [comment]
[<br/> support in diaries](https://trello.com/c/JlHuvh3F/216-br-support-in-diaries)

**Comment by Drapegnik** [comment]
[<br/> support in diaries](https://trello.com/c/JlHuvh3F/216-br-support-in-diaries)

**Comment by Drapegnik** [comment]
[Articles duplication bug due to pagination](https://trello.com/c/KEYgv9la/206-articles-duplication-bug-due-to-pagination)

**Comment by Drapegnik** [comment]
[add next articles page cache](https://trello.com/c/1tpHJLY5/220-add-next-articles-page-cache)

**Comment by Drapegnik** [comment]
[an 'unpublished' mark on tiles so that it is clear for admins which articles are available for them only](https://trello.com/c/XrkpJadk/116-an-unpublished-mark-on-tiles-so-that-it-is-clear-for-admins-which-articles-are-available-for-them-only)

**Comment by Drapegnik** [comment]
[Article tile: add publishing date and edit button](https://trello.com/c/7pgDujac/160-article-tile-add-publishing-date-and-edit-button)

**Comment by Drapegnik** [comment]
[temporary hide signup form](https://trello.com/c/UFy3n5x6/208-temporary-hide-signup-form)

**Comment by UladBohdan** [comment]
regarding the `!publishAt` issue:
the model contains:
`publishAt: {
      type: Date,
      default: Date.now,
    },`
so `publishAt` is never empty. Do we have examples of `publishAt` being absent?

I'll also make the fields `required` to be sure it's always presented.

**Review by tyndria — DISMISSED** [review]

**Review by UladBohdan — APPROVED** [review]

**Pull request merged**
