### PR TITLE
layout fixes + article collection note

### PR DESCRIPTION
**Pull request by andemerie**

### CODE REVIEW

**Comment by andemerie** [comment]
https://trello.com/c/CuIgumc0
https://trello.com/c/GIB0RwBt
https://trello.com/c/h2eJQAZM
https://trello.com/c/FVsTQlz9

**Comment by andemerie** [comment]
[to investigate collection articles order](https://trello.com/c/INke1LEo/463-to-investigate-collection-articles-order)

**Comment by andemerie** [comment]
https://trello.com/c/cRR4UApL

**Comment by andemerie** [comment]
depends on https://github.com/babajka/babajka-backend/pull/69

**Review by Drapegnik — DISMISSED** [review]

**Review by Drapegnik — APPROVED** [review]

**Pull request merged**
