### PR TITLE
Refactoring and updates

### PR DESCRIPTION
**Pull request by Drapegnik**
* update deps: `next@6`, `babel@7`, `react@16.4`
* use `Fragment` short syntax - `<></>`
* improve `BundleAnalyzer`
* enable `Google Analytics` only in `production`
* add `npm run local-styles` script that allow debug styles from markup repo 🔥 🔥 🔥

### CODE REVIEW

**Comment by Drapegnik** [comment]
[update dependencies](https://trello.com/c/LF4ShGGz/229-update-dependencies)

**Comment by Drapegnik** [comment]
[disable google analytics everywhere except prod after launch](https://trello.com/c/lBDSXyaz/226-disable-google-analytics-everywhere-except-prod-after-launch)

**Comment by Drapegnik** [comment]
[add support for reload styles on frontend locally](https://trello.com/c/t0aTgDu8/230-add-support-for-reload-styles-on-frontend-locally)

**Review by andemerie — APPROVED** [review]

**Comment by UladBohdan** [comment]
Local styles work for me👍

**Review by UladBohdan — APPROVED** [review]

**Comment by UladBohdan** [comment]
@Drapegnik so how do we enable Google Analytics now?
`__PROD__=true` set globally?

**Comment by Drapegnik** [comment]
@UladBohdan `NODE_ENV=production`, but it can be changed, for example with some other environment variable (`WIR_ENV=prod`)

**Pull request merged**
