### PR TITLE
Metatags

### PR DESCRIPTION
**Pull request by Drapegnik**
## default
screen shot 2018-11-14 at 03 28 31
screen shot 2018-11-14 at 03 28 37
screen shot 2018-11-14 at 03 28 43

## article
screen shot 2018-11-14 at 03 27 39
screen shot 2018-11-14 at 03 27 47
screen shot 2018-11-14 at 03 27 54

## twitter video
screen shot 2018-12-08 at 02 14 42

## telegram
screen shot 2018-11-14 at 04 42 44
screen shot 2018-11-14 at 04 41 05

## vk
screen shot 2018-11-14 at 04 39 25

# TODO
- [x] ~Fix twitter [player mode]~(https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/player-card)
- [ ] ~Fix fb [video mode](http://ogp.me/#type_video)~
- [ ] ~Fix vk video mode~
- [x] Add `fb:app_id`
- [x] Find out the right content on [`og:url`](http://ogp.me/#metadata) & `twitter:url` tags - to replace with local-free url
- [x] add redirect for missed locale: `/about` -> `/be/about`

### CODE REVIEW

**Comment by Drapegnik** [comment]
[make sure social networks render previews properly](https://trello.com/c/Ayy0MqkO/293-make-sure-social-networks-render-previews-properly)

**Comment by Drapegnik** [comment]
@UladBohdan, could you help me with it, please?

**Comment by UladBohdan** [comment]
* What's wrong with `og:url` and `twitter:url`? The problem is we're not passing it dynamically?
* Do you think we need to support `twitter:player`? This is for external players to be played within a tweet. And I doubt we want a lecture to play viewed from twitter. (And yes, again, we can't test twitter properly now due to robots.txt)
* FB does not render "play" sign but overall it looks fine. Does it render it at all, have you ever seen it?
* Does vk have a video mode?..

**Comment by UladBohdan** [comment]
also, that does not work fine right now for:

- [ ] /about
- [ ] /login

it default to main page. Looks not great.

**Comment by UladBohdan** [comment]
`og:url` seems to be a key only (fb uses fetched url to link)
* to check if it is the same for other platforms
* to replace with local-free url

**Review by UladBohdan — DISMISSED** [review]

**Comment by Drapegnik** [comment]
Save video metatags:
```js
export const MetaVideo = ({ url }) => (
  <Head>
    <meta key="meta-type-fb" property="og:type" content="video.other" />
    <meta key="meta-video-fb" property="og:video" content={url} />
    <meta key="meta-twi-card" name="twitter:card" content="player" />
    <meta key="meta-video-twi" name="twitter:player" content={url} />
    <meta key="meta-video-twi-width" name="twitter:player:width" content="480" />
    <meta key="meta-video-twi-height" name="twitter:player:height" content="480" />
  </Head>
);

MetaVideo.propTypes = {
  url: PropTypes.string.isRequired,
};
```

**Pull request merged**
